using System;

/// <summary>
/// One saved play record, mirroring the player_scores table in Supabase.
/// Field names must match the column names exactly - Unity's JsonUtility maps
/// them by name when reading rows back.
/// </summary>
[Serializable]
public class ScoreRecord
{
    public string player_id;    // uuid, generated by the database
    public string player_name;  // from NicknameManager
    public int score;           // words said correctly
    public int attempts;        // total voice attempts made
    public string level;        // e.g. "Bahay - Scene 1: Umaga na!"
    public string remarks;      // e.g. "3/5 words correct"
    public string created_at;   // timestamptz, defaulted by the database
}

/// <summary>
/// What actually gets POSTed when saving. Deliberately omits player_id and
/// created_at so the database fills them in with its own defaults
/// (gen_random_uuid() and now()) instead of us sending blanks.
/// </summary>
[Serializable]
public class ScoreInsert
{
    public string player_name;
    public int score;
    public int attempts;
    public string level;
    public string remarks;
}
